// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PasswordHasher is an autogenerated mock type for the PasswordHasher type
type PasswordHasher struct {
	mock.Mock
}

type PasswordHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *PasswordHasher) EXPECT() *PasswordHasher_Expecter {
	return &PasswordHasher_Expecter{mock: &_m.Mock}
}

// CompareHashAndPassword provides a mock function with given fields: hash, plain
func (_m *PasswordHasher) CompareHashAndPassword(hash string, plain string) bool {
	ret := _m.Called(hash, plain)

	if len(ret) == 0 {
		panic("no return value specified for CompareHashAndPassword")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(hash, plain)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// PasswordHasher_CompareHashAndPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompareHashAndPassword'
type PasswordHasher_CompareHashAndPassword_Call struct {
	*mock.Call
}

// CompareHashAndPassword is a helper method to define mock.On call
//   - hash string
//   - plain string
func (_e *PasswordHasher_Expecter) CompareHashAndPassword(hash interface{}, plain interface{}) *PasswordHasher_CompareHashAndPassword_Call {
	return &PasswordHasher_CompareHashAndPassword_Call{Call: _e.mock.On("CompareHashAndPassword", hash, plain)}
}

func (_c *PasswordHasher_CompareHashAndPassword_Call) Run(run func(hash string, plain string)) *PasswordHasher_CompareHashAndPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *PasswordHasher_CompareHashAndPassword_Call) Return(_a0 bool) *PasswordHasher_CompareHashAndPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PasswordHasher_CompareHashAndPassword_Call) RunAndReturn(run func(string, string) bool) *PasswordHasher_CompareHashAndPassword_Call {
	_c.Call.Return(run)
	return _c
}

// HashPassword provides a mock function with given fields: plain
func (_m *PasswordHasher) HashPassword(plain string) (string, error) {
	ret := _m.Called(plain)

	if len(ret) == 0 {
		panic("no return value specified for HashPassword")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(plain)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(plain)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(plain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PasswordHasher_HashPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashPassword'
type PasswordHasher_HashPassword_Call struct {
	*mock.Call
}

// HashPassword is a helper method to define mock.On call
//   - plain string
func (_e *PasswordHasher_Expecter) HashPassword(plain interface{}) *PasswordHasher_HashPassword_Call {
	return &PasswordHasher_HashPassword_Call{Call: _e.mock.On("HashPassword", plain)}
}

func (_c *PasswordHasher_HashPassword_Call) Run(run func(plain string)) *PasswordHasher_HashPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *PasswordHasher_HashPassword_Call) Return(_a0 string, _a1 error) *PasswordHasher_HashPassword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PasswordHasher_HashPassword_Call) RunAndReturn(run func(string) (string, error)) *PasswordHasher_HashPassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewPasswordHasher creates a new instance of PasswordHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPasswordHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *PasswordHasher {
	mock := &PasswordHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
