// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "auth-mytierlist/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// SessionsRepository is an autogenerated mock type for the SessionsRepository type
type SessionsRepository struct {
	mock.Mock
}

type SessionsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionsRepository) EXPECT() *SessionsRepository_Expecter {
	return &SessionsRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, s
func (_m *SessionsRepository) Create(ctx context.Context, s domain.RefreshSession) (uuid.UUID, error) {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.RefreshSession) (uuid.UUID, error)); ok {
		return rf(ctx, s)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.RefreshSession) uuid.UUID); ok {
		r0 = rf(ctx, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.RefreshSession) error); ok {
		r1 = rf(ctx, s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SessionsRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type SessionsRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - s domain.RefreshSession
func (_e *SessionsRepository_Expecter) Create(ctx interface{}, s interface{}) *SessionsRepository_Create_Call {
	return &SessionsRepository_Create_Call{Call: _e.mock.On("Create", ctx, s)}
}

func (_c *SessionsRepository_Create_Call) Run(run func(ctx context.Context, s domain.RefreshSession)) *SessionsRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.RefreshSession))
	})
	return _c
}

func (_c *SessionsRepository_Create_Call) Return(_a0 uuid.UUID, _a1 error) *SessionsRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SessionsRepository_Create_Call) RunAndReturn(run func(context.Context, domain.RefreshSession) (uuid.UUID, error)) *SessionsRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTokenHash provides a mock function with given fields: ctx, tokenHash
func (_m *SessionsRepository) GetByTokenHash(ctx context.Context, tokenHash string) (*domain.RefreshSession, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetByTokenHash")
	}

	var r0 *domain.RefreshSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.RefreshSession, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.RefreshSession); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RefreshSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SessionsRepository_GetByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTokenHash'
type SessionsRepository_GetByTokenHash_Call struct {
	*mock.Call
}

// GetByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *SessionsRepository_Expecter) GetByTokenHash(ctx interface{}, tokenHash interface{}) *SessionsRepository_GetByTokenHash_Call {
	return &SessionsRepository_GetByTokenHash_Call{Call: _e.mock.On("GetByTokenHash", ctx, tokenHash)}
}

func (_c *SessionsRepository_GetByTokenHash_Call) Run(run func(ctx context.Context, tokenHash string)) *SessionsRepository_GetByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SessionsRepository_GetByTokenHash_Call) Return(_a0 *domain.RefreshSession, _a1 error) *SessionsRepository_GetByTokenHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SessionsRepository_GetByTokenHash_Call) RunAndReturn(run func(context.Context, string) (*domain.RefreshSession, error)) *SessionsRepository_GetByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function with given fields: ctx, sessionID
func (_m *SessionsRepository) Revoke(ctx context.Context, sessionID uuid.UUID) error {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SessionsRepository_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type SessionsRepository_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
func (_e *SessionsRepository_Expecter) Revoke(ctx interface{}, sessionID interface{}) *SessionsRepository_Revoke_Call {
	return &SessionsRepository_Revoke_Call{Call: _e.mock.On("Revoke", ctx, sessionID)}
}

func (_c *SessionsRepository_Revoke_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *SessionsRepository_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *SessionsRepository_Revoke_Call) Return(_a0 error) *SessionsRepository_Revoke_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SessionsRepository_Revoke_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *SessionsRepository_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// Rotate provides a mock function with given fields: ctx, oldSessionID, newSession
func (_m *SessionsRepository) Rotate(ctx context.Context, oldSessionID uuid.UUID, newSession domain.RefreshSession) (uuid.UUID, error) {
	ret := _m.Called(ctx, oldSessionID, newSession)

	if len(ret) == 0 {
		panic("no return value specified for Rotate")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.RefreshSession) (uuid.UUID, error)); ok {
		return rf(ctx, oldSessionID, newSession)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.RefreshSession) uuid.UUID); ok {
		r0 = rf(ctx, oldSessionID, newSession)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, domain.RefreshSession) error); ok {
		r1 = rf(ctx, oldSessionID, newSession)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SessionsRepository_Rotate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rotate'
type SessionsRepository_Rotate_Call struct {
	*mock.Call
}

// Rotate is a helper method to define mock.On call
//   - ctx context.Context
//   - oldSessionID uuid.UUID
//   - newSession domain.RefreshSession
func (_e *SessionsRepository_Expecter) Rotate(ctx interface{}, oldSessionID interface{}, newSession interface{}) *SessionsRepository_Rotate_Call {
	return &SessionsRepository_Rotate_Call{Call: _e.mock.On("Rotate", ctx, oldSessionID, newSession)}
}

func (_c *SessionsRepository_Rotate_Call) Run(run func(ctx context.Context, oldSessionID uuid.UUID, newSession domain.RefreshSession)) *SessionsRepository_Rotate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(domain.RefreshSession))
	})
	return _c
}

func (_c *SessionsRepository_Rotate_Call) Return(_a0 uuid.UUID, _a1 error) *SessionsRepository_Rotate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SessionsRepository_Rotate_Call) RunAndReturn(run func(context.Context, uuid.UUID, domain.RefreshSession) (uuid.UUID, error)) *SessionsRepository_Rotate_Call {
	_c.Call.Return(run)
	return _c
}

// NewSessionsRepository creates a new instance of SessionsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionsRepository {
	mock := &SessionsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
