// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "auth-mytierlist/internal/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// TokenManager is an autogenerated mock type for the TokenManager type
type TokenManager struct {
	mock.Mock
}

type TokenManager_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenManager) EXPECT() *TokenManager_Expecter {
	return &TokenManager_Expecter{mock: &_m.Mock}
}

// IssueAccessToken provides a mock function with given fields: userID, role, ttl
func (_m *TokenManager) IssueAccessToken(userID uuid.UUID, role domain.Role, ttl time.Duration) (string, error) {
	ret := _m.Called(userID, role, ttl)

	if len(ret) == 0 {
		panic("no return value specified for IssueAccessToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, domain.Role, time.Duration) (string, error)); ok {
		return rf(userID, role, ttl)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, domain.Role, time.Duration) string); ok {
		r0 = rf(userID, role, ttl)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, domain.Role, time.Duration) error); ok {
		r1 = rf(userID, role, ttl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenManager_IssueAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueAccessToken'
type TokenManager_IssueAccessToken_Call struct {
	*mock.Call
}

// IssueAccessToken is a helper method to define mock.On call
//   - userID uuid.UUID
//   - role domain.Role
//   - ttl time.Duration
func (_e *TokenManager_Expecter) IssueAccessToken(userID interface{}, role interface{}, ttl interface{}) *TokenManager_IssueAccessToken_Call {
	return &TokenManager_IssueAccessToken_Call{Call: _e.mock.On("IssueAccessToken", userID, role, ttl)}
}

func (_c *TokenManager_IssueAccessToken_Call) Run(run func(userID uuid.UUID, role domain.Role, ttl time.Duration)) *TokenManager_IssueAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(domain.Role), args[2].(time.Duration))
	})
	return _c
}

func (_c *TokenManager_IssueAccessToken_Call) Return(_a0 string, _a1 error) *TokenManager_IssueAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenManager_IssueAccessToken_Call) RunAndReturn(run func(uuid.UUID, domain.Role, time.Duration) (string, error)) *TokenManager_IssueAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenManager creates a new instance of TokenManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenManager {
	mock := &TokenManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
