// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "auth-mytierlist/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"

	usecase "auth-mytierlist/internal/usecase"

	uuid "github.com/google/uuid"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

type AuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthService) EXPECT() *AuthService_Expecter {
	return &AuthService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, login, password
func (_m *AuthService) Login(ctx context.Context, login string, password string) (*usecase.AuthTokens, error) {
	ret := _m.Called(ctx, login, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *usecase.AuthTokens
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*usecase.AuthTokens, error)); ok {
		return rf(ctx, login, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *usecase.AuthTokens); ok {
		r0 = rf(ctx, login, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.AuthTokens)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, login, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - password string
func (_e *AuthService_Expecter) Login(ctx interface{}, login interface{}, password interface{}) *AuthService_Login_Call {
	return &AuthService_Login_Call{Call: _e.mock.On("Login", ctx, login, password)}
}

func (_c *AuthService_Login_Call) Run(run func(ctx context.Context, login string, password string)) *AuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *AuthService_Login_Call) Return(_a0 *usecase.AuthTokens, _a1 error) *AuthService_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_Login_Call) RunAndReturn(run func(context.Context, string, string) (*usecase.AuthTokens, error)) *AuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, refreshToken
func (_m *AuthService) Logout(ctx context.Context, refreshToken string) error {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type AuthService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *AuthService_Expecter) Logout(ctx interface{}, refreshToken interface{}) *AuthService_Logout_Call {
	return &AuthService_Logout_Call{Call: _e.mock.On("Logout", ctx, refreshToken)}
}

func (_c *AuthService_Logout_Call) Run(run func(ctx context.Context, refreshToken string)) *AuthService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AuthService_Logout_Call) Return(_a0 error) *AuthService_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthService_Logout_Call) RunAndReturn(run func(context.Context, string) error) *AuthService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Me provides a mock function with given fields: ctx, userID
func (_m *AuthService) Me(ctx context.Context, userID uuid.UUID) (*domain.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Me")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_Me_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Me'
type AuthService_Me_Call struct {
	*mock.Call
}

// Me is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *AuthService_Expecter) Me(ctx interface{}, userID interface{}) *AuthService_Me_Call {
	return &AuthService_Me_Call{Call: _e.mock.On("Me", ctx, userID)}
}

func (_c *AuthService_Me_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *AuthService_Me_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AuthService_Me_Call) Return(_a0 *domain.User, _a1 error) *AuthService_Me_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_Me_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.User, error)) *AuthService_Me_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function with given fields: ctx, refreshToken
func (_m *AuthService) Refresh(ctx context.Context, refreshToken string) (*usecase.AuthTokens, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 *usecase.AuthTokens
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*usecase.AuthTokens, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *usecase.AuthTokens); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.AuthTokens)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type AuthService_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *AuthService_Expecter) Refresh(ctx interface{}, refreshToken interface{}) *AuthService_Refresh_Call {
	return &AuthService_Refresh_Call{Call: _e.mock.On("Refresh", ctx, refreshToken)}
}

func (_c *AuthService_Refresh_Call) Run(run func(ctx context.Context, refreshToken string)) *AuthService_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AuthService_Refresh_Call) Return(_a0 *usecase.AuthTokens, _a1 error) *AuthService_Refresh_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_Refresh_Call) RunAndReturn(run func(context.Context, string) (*usecase.AuthTokens, error)) *AuthService_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, login, password
func (_m *AuthService) Register(ctx context.Context, login string, password string) (*usecase.AuthTokens, error) {
	ret := _m.Called(ctx, login, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *usecase.AuthTokens
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*usecase.AuthTokens, error)); ok {
		return rf(ctx, login, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *usecase.AuthTokens); ok {
		r0 = rf(ctx, login, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.AuthTokens)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, login, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type AuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - password string
func (_e *AuthService_Expecter) Register(ctx interface{}, login interface{}, password interface{}) *AuthService_Register_Call {
	return &AuthService_Register_Call{Call: _e.mock.On("Register", ctx, login, password)}
}

func (_c *AuthService_Register_Call) Run(run func(ctx context.Context, login string, password string)) *AuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *AuthService_Register_Call) Return(_a0 *usecase.AuthTokens, _a1 error) *AuthService_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_Register_Call) RunAndReturn(run func(context.Context, string, string) (*usecase.AuthTokens, error)) *AuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
